version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Tenant
    ports:
      - "3308:3306"  # Change this line
    volumes:
      - mysql_data:/var/lib/mysql

  flask:
    build: .
    container_name: flask-app
    command: python app.py
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      FLASK_ENV: development

volumes:
  mysql_data:
