FROM mysql:8.0-debian


SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

ENV SHELL=/bin/bash 
ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /

ENV MYSQL_DATABASE=Tenant


#basic installation
RUN apt-get update --yes && \
    apt-get upgrade --yes && \
    apt-get install python3.11-dev python3.11-venv pip curl git wget ca-certificates -y --no-install-recommends && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    mkdir /app

# setting up python commands
RUN ln -s /usr/bin/python3.11 /usr/bin/python && \
    rm /usr/bin/python3 &&\
    ln -s /usr/bin/python3.11 /usr/bin/python3 && \
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py && \
    python get-pip.py

# setting python path
RUN python -m venv /venv
ENV PATH="/venv/bin:$PATH"

COPY tenant.sql /docker-entrypoint-initdb.d/

COPY . /app

# Upgrading pip and othe basic modules
RUN pip install --upgrade --no-cache-dir pip && \
    pip install --upgrade setuptools && \
    pip install --upgrade wheel && \
    cd /app && \
    pip install -r requirements.txt

EXPOSE 5000

# CMD ["/bin/bash"]
